<a href="https://colab.research.google.com/github/avxsharma-glitch/Python-Libraries/blob/main/Vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1. Create two vectors using the random function
vector1 = np.random.rand(5)  # A 5-element random vector
vector2 = np.random.rand(5)  # Another 5-element random vector

print("Vector 1:", vector1)
print("Vector 2:", vector2)

# 2. Merge them into a single matrix using the column_stack function
matrix = np.column_stack((vector1, vector2))

print("\nMatrix created using column_stack:")
print(matrix)

# 3. Decompose the matrix into Q and R matrices using QR decomposition
Q, R = np.linalg.qr(matrix)

print("\nQ matrix (orthogonal matrix):")
print(Q)

print("\nR matrix (upper triangular matrix):")
print(R)

# Verify decomposition (optional: A = Q @ R)
# print("\nVerification (Q @ R):")
# print(Q @ R)

Vector 1: [0.10143939 0.95804339 0.39009832 0.22582154 0.43490426]
Vector 2: [0.55296937 0.21002135 0.21637516 0.7321803  0.5222335 ]

Matrix created using column_stack:
[[0.10143939 0.55296937]
 [0.95804339 0.21002135]
 [0.39009832 0.21637516]
 [0.22582154 0.7321803 ]
 [0.43490426 0.5222335 ]]

Q matrix (orthogonal matrix):
[[-8.82765825e-02  5.56114545e-01]
 [-8.33727364e-01 -3.61343658e-01]
 [-3.39479034e-01 -5.82798474e-04]
 [-1.96518864e-01  6.79365786e-01]
 [-3.78470937e-01  3.14052805e-01]]

R matrix (upper triangular matrix):
[[-1.14910873 -0.63890706]
 [ 0.          0.89292546]]
